### ISSUE TITLE
error installing?

### ISSUE THREAD

**Issue by tofutim** [acvetkov/download-crx#1]
Hi, I am thinking about using this in a build script, but I ran into the following

> > npm install --save-dev download-crx
> > npm WARN publish@1.0.0 No description
> > npm WARN publish@1.0.0 No repository field.
> > npm ERR! Windows_NT 6.3.9600
> > npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
> > tall" "--save-dev" "download-crx"
> > npm ERR! node v6.3.0
> > npm ERR! npm  v3.10.3
> > npm ERR! path D:\xxx\Add-ons\yyy\src\publish\node_modules\download-crx\bind\download
> > npm ERR! code ENOENT
> > npm ERR! errno -4058
> > npm ERR! syscall chmod
> 
> npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\xxx\Add-ons\yyy\src\publish\node_modules\downlo
> ad-crx\bind\download'
> npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\xxx\Add-ons\yyy\src\publish\node_modules\downlo
> ad-crx\bind\download'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\xxx\Add-ons\yyy\src\publish\npm-debug.log

I get the same error if I 'npm install download-crx' instead of --save-dev, so something is amiss.

**Comment by tofutim** [comment]
I see the problem, package.json is pointing to "bind/download" instead of "bin/download"

**Comment by acvetkov** [comment]
https://github.com/acvetkov/download-crx/pull/2

**Comment by acvetkov** [comment]
I have updated npm package with version 1.0.1
